#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : python-zaqarclient
Version  : 1.11.0
Release  : 19
URL      : http://tarballs.openstack.org/python-zaqarclient/python-zaqarclient-1.11.0.tar.gz
Source0  : http://tarballs.openstack.org/python-zaqarclient/python-zaqarclient-1.11.0.tar.gz
Source99 : http://tarballs.openstack.org/python-zaqarclient/python-zaqarclient-1.11.0.tar.gz.asc
Summary  : Client Library for OpenStack Zaqar Messaging API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-zaqarclient-license = %{version}-%{release}
Requires: python-zaqarclient-python = %{version}-%{release}
Requires: python-zaqarclient-python3 = %{version}-%{release}
Requires: Sphinx
Requires: jsonschema
Requires: keystoneauth1
Requires: openstackdocstheme
Requires: os-client-config
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: pbr
Requires: reno
Requires: requests
Requires: requests-mock
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
Team and repository tags
        ========================

%package license
Summary: license components for the python-zaqarclient package.
Group: Default

%description license
license components for the python-zaqarclient package.


%package python
Summary: python components for the python-zaqarclient package.
Group: Default
Requires: python-zaqarclient-python3 = %{version}-%{release}

%description python
python components for the python-zaqarclient package.


%package python3
Summary: python3 components for the python-zaqarclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-zaqarclient package.


%prep
%setup -q -n python-zaqarclient-1.11.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540479454
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-zaqarclient
cp LICENSE %{buildroot}/usr/share/package-licenses/python-zaqarclient/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-zaqarclient/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
