#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F398DEAE440091C (infra-root@openstack.org)
#
Name     : python-zaqarclient
Version  : 1.13.0
Release  : 29
URL      : http://tarballs.openstack.org/python-zaqarclient/python-zaqarclient-1.13.0.tar.gz
Source0  : http://tarballs.openstack.org/python-zaqarclient/python-zaqarclient-1.13.0.tar.gz
Source1  : http://tarballs.openstack.org/python-zaqarclient/python-zaqarclient-1.13.0.tar.gz.asc
Summary  : Client Library for OpenStack Zaqar Messaging API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-zaqarclient-license = %{version}-%{release}
Requires: python-zaqarclient-python = %{version}-%{release}
Requires: python-zaqarclient-python3 = %{version}-%{release}
Requires: jsonschema
Requires: keystoneauth1
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : jsonschema
BuildRequires : keystoneauth1
BuildRequires : osc-lib
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : requests
BuildRequires : six
BuildRequires : stevedore

%description
========================
Team and repository tags
========================

.. image:: http://governance.openstack.org/tc/badges/python-zaqarclient.svg
    :target: http://governance.openstack.org/tc/reference/tags/index.html

.. Change things from this point on

Python Zaqar Client
===================

.. image:: https://img.shields.io/pypi/v/python-zaqarclient.svg
    :target: https://pypi.org/project/python-zaqarclient/
    :alt: Latest Version

:Wiki: `Zaqar Wiki`_
:Launchpad: `Zaqar Launchpad`_
:Review: `Code Review`_
:Design: `Client Wiki`_
:IRC: #openstack-zaqar @ freenode

Welcome to the `Zaqar`_ Python Client project!

Installation
------------

The latest stable release can be installed from PyPI::

    pip install --upgrade python-zaqarclient

For the adventurous, you may also install the latest code directly from git
.openstack.org::

    pip install git+https://git.openstack.org/openstack/python-zaqarclient.git

What's in the box
-----------------

By installing python-zaqarclient you get programmatic access to the Zaqar v1.0
API library. Plus, it installs a plugin to python-openstackclient that allows
you to perform simple queue operations.

How to use
==========

Python client
-------------

Details about design, features, usage and workflow can be found in the
`Python Client Wiki`_.

.. _Python Client Wiki: https://wiki.openstack.org/wiki/Zaqar/PythonClient

Command line interface
----------------------

Zaqar bases its client implementation in the `OpenStack Client`_. It can be
installed and configured by following the instructions in *Getting Started*
and *Configuration* in the `OpenStack Client Readme`_ respectively.

The CLI currently allows creation, removal and listing of queues. Some examples
are::

    $  openstack queue list --limit 3
    $  openstack queue create myqueue
    $  openstack queue delete myqueue

.. _`OpenStack Client`: https://git.openstack.org/cgit/openstack/python-openstackclient
.. _`OpenStack Client Readme`: https://git.openstack.org/cgit/openstack/python-openstackclient/tree/README.rst

Contributing
============

Be sure to reference the `HACKING`_ file for details on coding style. You may
also wish to read through Zaqar's `Contributor Guide`_ before contributing your
first patch.

.. _Zaqar: https://git.openstack.org/cgit/openstack/zaqar
.. _HACKING: https://git.openstack.org/cgit/openstack/python-zaqarclient/tree/HACKING.rst
.. _Zaqar Wiki: https://wiki.openstack.org/wiki/Zaqar
.. _Contributor Guide: https://wiki.openstack.org/wiki/Zaqar#Contributor_Guide
.. _Zaqar Launchpad: https://launchpad.net/zaqar
.. _Code Review: https://review.openstack.org/#/q/status:open+project:openstack/python-zaqarclient,n,z
.. _Client Wiki: https://wiki.openstack.org/wiki/Python_Zaqar_Client


* License: Apache License, Version 2.0
* `PyPi`_ - package installation
* `Bugs`_ - issue tracking
* `Source`_

.. _PyPi: https://pypi.org/project/python-zaqarclient
.. _Bugs: https://bugs.launchpad.net/python-zaqarclient
.. _Source: https://git.openstack.org/cgit/openstack/python-zaqarclient

%package license
Summary: license components for the python-zaqarclient package.
Group: Default

%description license
license components for the python-zaqarclient package.


%package python
Summary: python components for the python-zaqarclient package.
Group: Default
Requires: python-zaqarclient-python3 = %{version}-%{release}

%description python
python components for the python-zaqarclient package.


%package python3
Summary: python3 components for the python-zaqarclient package.
Group: Default
Requires: python3-core
Provides: pypi(python-zaqarclient)

%description python3
python3 components for the python-zaqarclient package.


%prep
%setup -q -n python-zaqarclient-1.13.0
cd %{_builddir}/python-zaqarclient-1.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583215895
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-zaqarclient
cp %{_builddir}/python-zaqarclient-1.13.0/LICENSE %{buildroot}/usr/share/package-licenses/python-zaqarclient/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-zaqarclient/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
